# Generated by Django 5.1.4 on 2025-01-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('passengers', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
